### ISSUE TITLE
p100 power status default on

### ISSUE THREAD

**Issue by maxeq** [diskxo/house-manager#1]
I have a problem, I really like Tapo  P100 and want to change my starting status.

My problem is that after a power outage, the p100 does not remember theprevious state and is always turned off.

How do I changeit ?  Is there any setting for a power outage?

**Comment by diskxo** [comment]
I think it's not possible with my libraries to remember the previous state...
if I understand what you are asking me you could create a json file that automatically updates itself and inserts the status of the socket ...
